apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-react-deployments
  name: my-react-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-deployments
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-react-deployments
    spec:
      containers:
      - image: vaibhav220622/react_jenkins:v1
        name: my-react-app-latestss
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 5000

status: {}
