apiVersion: v1
kind: Service
metadata:
  name: my-react-service
spec:
  type: NodePort      
  selector:
    app: my-react-deployments
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
